# Generated by Django 4.2.2 on 2023-10-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_suite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='linnncode.testsuite'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('test_case', models.TextField()),
                ('solution', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='linnncode.solution')),
            ],
        ),
        migrations.AddField(
            model_name='testsuite',
            name='test_cases',
            field=models.ManyToManyField(related_name='suite', to='linnncode.testcase'),
        ),
    ]
