# Generated by Django 4.2.2 on 2023-10-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0002_problem_description_problem_test_suite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='linnncode.testsuite'),
        ),
    ]
