# Generated by Django 4.2.2 on 2023-10-01 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0003_remove_testsuite_test_cases_testcase_test_suite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='test_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='linnncode.testcase'),
        ),
    ]
