# Generated by Django 4.2.2 on 2023-10-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0004_remove_testcase_solution_solution_test_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='test_registration',
            field=models.TextField(null=True),
        ),
    ]
