# Generated by Django 4.2.2 on 2023-10-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0005_testsuite_test_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
