# Generated by Django 4.1.5 on 2023-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0006_delete_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='test_registration',
        ),
    ]
