# Generated by Django 4.1.5 on 2023-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0007_submission_remove_testcase_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
