# Generated by Django 4.1.5 on 2023-10-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linnncode', '0011_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='users',
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
