# Generated by Django 4.2.6 on 2023-10-11 23:57

from django.db import migrations, models
import linnncode.models


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0015_submission_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.ImageField(default=linnncode.models.get_default_image, upload_to='images/'),
        ),
    ]
