# Generated by Django 4.2.6 on 2023-10-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnncode', '0016_problem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
